// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrfkB8saOKCbMYkHerhAuShDy5QRbIl9I',
    appId: '1:581424691991:web:9991fe0acb7f6ecffb1552',
    messagingSenderId: '581424691991',
    projectId: 'bluezoneapp1-43668',
    authDomain: 'bluezoneapp1-43668.firebaseapp.com',
    storageBucket: 'bluezoneapp1-43668.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABNNkHlLHmlfzwIiJhWuVC97u0JqUVrH0',
    appId: '1:581424691991:android:e50bed1722f0dcb7fb1552',
    messagingSenderId: '581424691991',
    projectId: 'bluezoneapp1-43668',
    storageBucket: 'bluezoneapp1-43668.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWUXi58D-0jlLKgLm4o7vCKpi7gaMVtEk',
    appId: '1:581424691991:ios:7d3d5d0d722c8f64fb1552',
    messagingSenderId: '581424691991',
    projectId: 'bluezoneapp1-43668',
    storageBucket: 'bluezoneapp1-43668.firebasestorage.app',
    iosBundleId: 'com.example.blueZone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWUXi58D-0jlLKgLm4o7vCKpi7gaMVtEk',
    appId: '1:581424691991:ios:7d3d5d0d722c8f64fb1552',
    messagingSenderId: '581424691991',
    projectId: 'bluezoneapp1-43668',
    storageBucket: 'bluezoneapp1-43668.firebasestorage.app',
    iosBundleId: 'com.example.blueZone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrfkB8saOKCbMYkHerhAuShDy5QRbIl9I',
    appId: '1:581424691991:web:3624759cfa96ec33fb1552',
    messagingSenderId: '581424691991',
    projectId: 'bluezoneapp1-43668',
    authDomain: 'bluezoneapp1-43668.firebaseapp.com',
    storageBucket: 'bluezoneapp1-43668.firebasestorage.app',
  );
}
